{{flutter_js}}
{{flutter_build_config}}

async function startWeatherApp() {
  // Generated by tool/run.ps1; keys used in browser applications are public.
  try {
    const response = await fetch('maps-config.json', {cache: 'no-store'});
    if (response.ok) {
      const config = await response.json();
      if (config.GOOGLE_MAPS_API_KEY) {
        await new Promise((resolve, reject) => {
          const script = document.createElement('script');
          script.src = 'https://maps.googleapis.com/maps/api/js?key=' +
            encodeURIComponent(config.GOOGLE_MAPS_API_KEY);
          script.onload = resolve;
          script.onerror = reject;
          document.head.appendChild(script);
        });
      }
    }
  } catch (error) {
    console.error('Google Maps could not be loaded', error);
  }
  if ('serviceWorker' in navigator) {
    navigator.serviceWorker.register('sw.js').catch(console.error);
  }
  _flutter.loader.load();
}
startWeatherApp();
